### ISSUE TITLE
Uncaught (in promise) Error: The send transactions "from" field must be defined!

### ISSUE THREAD

**Issue by ghost** [dappuniversity/eth-todo-list#20]
I ran into an error like this.

Uncaught (in promise) Error: The send transactions "from" field must be defined!
    at Object.createTask (app.js:98:28)
    at HTMLFormElement.onsubmit (（index）:53:74)

this is my createtask.
createTask: async () => {
        App.setLoading(true)
        const content = $('#newTask').val()
        await App.todoList.createTask(content, {from: App.account})
        window.location.reload()
    },

index
` <div class="container-fluid">
        <div class="row">
            <main role="main" class="d-flex col-lg-12 justify-content-center">
                <div id="loader" class="text-center">
                    <p class="text-center">Loading...</p>
                </div>
                <div id="content">
                    <form onsubmit="App.createTask(); return false;">
                        <input type="text" class="form-control" id="newTask" placeholder="Add new task.." required>
                        <input type="submit" hidden="">
                    </form>
                    <ul id="taskList" class="list-unstyled">
                        <div id="taskTemplate" class="checkbox" style="display: none">
                            <label>
                                <input type="checkbox">
                                <span class="content">Task content...</span>
                            </label>
                        </div>
                    </ul>
                    <ul id="completedTaskList" class="list-unstyled">
                    </ul>
                </div>
            </main>
        </div>
    </div>`

help me

**Comment by ghost** [comment]
when I tried [this](https://github.com/dappuniversity/eth-todo-list/issues/19), I ran another error.
like this.
Uncaught (in promise) Error: Returned error: sender account not recognized
    at Object.createTask (app.js:98:28)

**Comment by ghost** [comment]
This was a problem on the metamask side. I solved it.
